name: CI Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  buildtest:
    runs-on: ubuntu-20.04

    env:
      XDEBUG_MODE: coverage

    services:
      nextcloud:
        image: nextcloud
        env:
          SQLITE_DATABASE: /tmp/nextcloud.db
          NEXTCLOUD_ADMIN_USER: ncadm
          NEXTCLOUD_ADMIN_PASSWORD: ncadmPassw0rd
        ports:
          - 8080:80

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2
          extensions: gd, xdebug, curl
          coverage: xdebug
      - name: Checkout carddavclient
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer update --no-interaction --no-progress
      - name: Check code style compliance with PSR12
        run: make stylecheck
      - name: Check code compatibility with minimum supported PHP version
        run: make phpcompatcheck
      - name: Run psalm static analysis
        run: make psalmanalysis
      - name: Run tests
        run: make tests
